pub mod ai_commands;
pub mod audio;
pub mod claude;
pub mod commands;
pub mod diarization;
pub mod diarization_commands;
pub mod error;
pub mod search_commands;
pub mod storage;
pub mod whisper;

#[cfg(test)]
pub mod test_helpers;

#[cfg(test)]
mod integration_tests;

use std::sync::{Arc, Mutex};

use tauri::Manager;

use ai_commands::{
    generate_minutes, investigate, run_ai_batch, start_ai_analysis, stop_ai_analysis, AiState,
};
use commands::{
    check_screen_capture_permission, create_session, end_session, focus_main_window,
    get_capture_state, health_check, pause_audio_capture, resume_audio_capture,
    start_audio_capture, stop_audio_capture, toggle_mini_view, AppState,
};
use diarization_commands::{
    get_speakers, run_diarization, start_diarization, stop_diarization, DiarizationState,
};
use error::AppError;
use search_commands::{get_all_settings, get_setting, search_transcripts, set_setting};

/// Run the Tauri application.
///
/// # Errors
///
/// Returns an error if the Tauri runtime fails to start.
pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    let specta_builder =
        tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
            health_check,
            start_audio_capture,
            stop_audio_capture,
            pause_audio_capture,
            resume_audio_capture,
            get_capture_state,
            create_session,
            end_session,
            check_screen_capture_permission,
            start_ai_analysis,
            stop_ai_analysis,
            run_ai_batch,
            investigate,
            generate_minutes,
            start_diarization,
            stop_diarization,
            run_diarization,
            get_speakers,
            toggle_mini_view,
            focus_main_window,
            search_transcripts,
            get_setting,
            set_setting,
            get_all_settings,
        ]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("/* eslint-disable */\n// This file was generated by tauri-specta. Do not edit."),
            "../src/bindings.ts",
        )
        .map_err(|e| format!("Failed to export TypeScript bindings: {e}"))?;

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);

            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir).map_err(|e| AppError::Storage(e.to_string()))?;
            let db_path = data_dir.join("mojiokoshi.db");
            let db_path_str = db_path
                .to_str()
                .ok_or_else(|| AppError::Storage("Invalid DB path".to_string()))?;

            let db = Arc::new(storage::sqlite::SqliteStorage::new(db_path_str)?);
            let bridge = Arc::new(claude::ClaudeCodeBridge::new());

            app.manage(AppState {
                capture: Mutex::new(audio::screen_capture::ScreenCaptureKitCapture::new()),
                storage: Arc::clone(&db),
            });

            app.manage(AiState {
                bridge,
                storage: Arc::clone(&db),
                batch_processor: Mutex::new(None),
            });

            app.manage(DiarizationState {
                bridge: Mutex::new(diarization::PyannoteBridge::new()),
            });

            app.manage(db);

            Ok(())
        })
        .run(tauri::generate_context!())?;

    Ok(())
}
