pub mod ai_commands;
pub mod audio;
pub mod claude;
pub mod commands;
pub mod diarization;
pub mod diarization_commands;
pub mod error;
pub mod export;
pub mod export_commands;
pub mod keyword_dictionary_commands;
pub mod meeting_link_commands;
pub mod search_commands;
pub mod sentiment_commands;
pub mod storage;
pub mod translation_commands;
pub mod whisper;

#[cfg(test)]
pub mod test_helpers;

#[cfg(test)]
mod integration_tests;

use std::sync::{Arc, Mutex};

use tauri::Manager;

use ai_commands::{
    generate_minutes, investigate, run_ai_batch, start_ai_analysis, stop_ai_analysis, AiState,
};
use commands::{
    check_screen_capture_permission, check_sidecar_status, create_session, download_whisper_model,
    end_session, focus_main_window, get_capture_state, get_whisper_model_status, health_check,
    pause_audio_capture, resume_audio_capture, start_audio_capture, stop_audio_capture,
    toggle_mini_view, AppState,
};
use diarization_commands::{
    get_speakers, run_diarization, start_diarization, stop_diarization, update_speaker_label,
    DiarizationState,
};
use error::AppError;
use export_commands::{export_markdown, save_export_file};
use keyword_dictionary_commands::{
    add_dictionary_keyword, delete_dictionary_keyword, get_all_dictionary_keywords,
    update_dictionary_keyword,
};
use meeting_link_commands::{find_related_meetings, get_meeting_links};
use search_commands::{get_all_settings, get_setting, search_transcripts, set_setting};
use sentiment_commands::{analyze_sentiment, get_sentiments};
use translation_commands::{get_translations, translate_segments};

/// Run the Tauri application.
///
/// # Errors
///
/// Returns an error if the Tauri runtime fails to start.
pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    let specta_builder =
        tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
            health_check,
            start_audio_capture,
            stop_audio_capture,
            pause_audio_capture,
            resume_audio_capture,
            get_capture_state,
            create_session,
            end_session,
            check_screen_capture_permission,
            start_ai_analysis,
            stop_ai_analysis,
            run_ai_batch,
            investigate,
            generate_minutes,
            start_diarization,
            stop_diarization,
            run_diarization,
            get_speakers,
            update_speaker_label,
            toggle_mini_view,
            focus_main_window,
            search_transcripts,
            get_setting,
            set_setting,
            get_all_settings,
            export_markdown,
            save_export_file,
            translate_segments,
            get_translations,
            find_related_meetings,
            get_meeting_links,
            analyze_sentiment,
            get_sentiments,
            add_dictionary_keyword,
            update_dictionary_keyword,
            delete_dictionary_keyword,
            get_all_dictionary_keywords,
            check_sidecar_status,
            get_whisper_model_status,
            download_whisper_model,
        ]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("/* eslint-disable */\n// This file was generated by tauri-specta. Do not edit."),
            "../src/bindings.ts",
        )
        .map_err(|e| format!("Failed to export TypeScript bindings: {e}"))?;

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);

            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir).map_err(|e| AppError::Storage(e.to_string()))?;
            let db_path = data_dir.join("mojiokoshi.db");
            let db_path_str = db_path
                .to_str()
                .ok_or_else(|| AppError::Storage("Invalid DB path".to_string()))?;

            let db = Arc::new(storage::sqlite::SqliteStorage::new(db_path_str)?);
            let bridge = Arc::new(claude::ClaudeCodeBridge::new());

            let whisper_model = whisper::model::model_path(&data_dir, "base");
            let vad_path = app
                .path()
                .resource_dir()
                .map_err(|e| AppError::Config(e.to_string()))?
                .join("resources/silero_vad.onnx");

            let models = if whisper_model.exists() && vad_path.exists() {
                whisper::load_models(&whisper_model.to_string_lossy(), &vad_path).ok()
            } else {
                None
            };
            let (recognizer, vad) = match models {
                Some((r, v)) => (Some(r), Some(v)),
                None => (None, None),
            };

            app.manage(AppState {
                capture: Mutex::new(audio::screen_capture::ScreenCaptureKitCapture::new()),
                storage: Arc::clone(&db),
                pipeline_shutdown: Arc::new(std::sync::atomic::AtomicBool::new(false)),
                pipeline_handle: Mutex::new(None),
                vad: Mutex::new(vad),
                recognizer: Mutex::new(recognizer),
            });

            app.manage(AiState {
                bridge,
                storage: Arc::clone(&db),
                batch_processor: Mutex::new(None),
            });

            app.manage(DiarizationState {
                bridge: Mutex::new(diarization::PyannoteBridge::new()),
            });

            app.manage(db);

            Ok(())
        })
        .run(tauri::generate_context!())?;

    Ok(())
}
