pub mod ai_commands;
pub mod audio;
pub mod bookmark_commands;
pub mod claude;
pub mod commands;
pub mod diarization;
pub mod diarization_commands;
pub mod error;
pub mod export;
pub mod export_commands;
pub mod search_commands;
pub mod storage;
pub mod whisper;

#[cfg(test)]
pub mod test_helpers;

#[cfg(test)]
mod integration_tests;

use log::info;
use std::sync::{Arc, Mutex};

use tauri::Manager;

use ai_commands::{
    format_transcript, generate_minutes, investigate, run_ai_batch, start_ai_analysis,
    stop_ai_analysis, suggest_questions, AiState,
};
use bookmark_commands::{add_bookmark, get_bookmarks, remove_bookmark};
use commands::{
    check_screen_capture_permission, check_sidecar_status, create_session, download_whisper_model,
    end_session, focus_main_window, get_capture_state, get_whisper_model_status, health_check,
    pause_audio_capture, resume_audio_capture, start_audio_capture, stop_audio_capture,
    toggle_mini_view, AppState,
};
use diarization_commands::{
    get_speakers, run_diarization, start_diarization, stop_diarization, update_speaker_label,
    DiarizationState,
};
use error::AppError;
use export_commands::{export_markdown, export_pdf, save_export_file};
use search_commands::{
    get_all_settings, get_setting, rebuild_search_index, search_transcripts, set_setting,
};

/// Run the Tauri application.
///
/// # Errors
///
/// Returns an error if the Tauri runtime fails to start.
pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    let specta_builder =
        tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
            health_check,
            start_audio_capture,
            stop_audio_capture,
            pause_audio_capture,
            resume_audio_capture,
            get_capture_state,
            create_session,
            end_session,
            check_screen_capture_permission,
            start_ai_analysis,
            stop_ai_analysis,
            run_ai_batch,
            investigate,
            generate_minutes,
            format_transcript,
            suggest_questions,
            start_diarization,
            stop_diarization,
            run_diarization,
            get_speakers,
            update_speaker_label,
            toggle_mini_view,
            focus_main_window,
            search_transcripts,
            get_setting,
            set_setting,
            get_all_settings,
            export_markdown,
            save_export_file,
            check_sidecar_status,
            get_whisper_model_status,
            download_whisper_model,
            add_bookmark,
            remove_bookmark,
            get_bookmarks,
            export_pdf,
            rebuild_search_index,
        ]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("/* eslint-disable */\n// This file was generated by tauri-specta. Do not edit."),
            "../src/bindings.ts",
        )
        .map_err(|e| format!("Failed to export TypeScript bindings: {e}"))?;

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info"))
                .init();
            info!("MojiOkoshi backend starting");

            specta_builder.mount_events(app);

            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir).map_err(|e| AppError::Storage(e.to_string()))?;
            let db_path = data_dir.join("mojiokoshi.db");
            let db_path_str = db_path
                .to_str()
                .ok_or_else(|| AppError::Storage("Invalid DB path".to_string()))?;

            let db = Arc::new(storage::sqlite::SqliteStorage::new(db_path_str)?);
            let bridge = Arc::new(claude::ClaudeCodeBridge::new());

            let preferred_model = db
                .get_setting("whisperModel")
                .ok()
                .flatten()
                .unwrap_or_else(|| "large-v3-turbo".to_string());
            info!("Preferred whisper model: {preferred_model}");
            let whisper_model = whisper::model::model_path(&data_dir, &preferred_model);
            let vad_path = app
                .path()
                .resource_dir()
                .map_err(|e| AppError::Config(e.to_string()))?
                .join("resources/silero_vad.onnx");

            let models = if whisper_model.exists() && vad_path.exists() {
                whisper::load_models(&whisper_model.to_string_lossy(), &vad_path).ok()
            } else {
                None
            };
            let (recognizer, vad) = match models {
                Some((r, v)) => (Some(r), Some(v)),
                None => (None, None),
            };

            if recognizer.is_some() {
                info!("Whisper model loaded successfully");
            } else {
                log::warn!(
                    "Whisper model not loaded at startup (model file: {})",
                    whisper_model.display()
                );
            }

            app.manage(AppState {
                capture: Mutex::new(audio::screen_capture::ScreenCaptureKitCapture::new()),
                storage: Arc::clone(&db),
                pipeline_shutdown: Arc::new(std::sync::atomic::AtomicBool::new(false)),
                pipeline_handle: Mutex::new(None),
                vad: Mutex::new(vad),
                recognizer: Mutex::new(recognizer),
            });

            app.manage(AiState {
                bridge,
                storage: Arc::clone(&db),
                batch_processor: Mutex::new(None),
                last_format_end_ms: Mutex::new(0.0),
                last_formatted_text: Mutex::new(None),
            });

            app.manage(DiarizationState {
                bridge: Mutex::new(diarization::PyannoteBridge::new()),
            });

            app.manage(db);

            Ok(())
        })
        .run(tauri::generate_context!())?;

    Ok(())
}
