/* eslint-disable */
// This file was generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCaptureState() : Promise<Result<CaptureState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_capture_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSession(title: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endSession(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkScreenCapturePermission() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_screen_capture_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAiAnalysis(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_ai_analysis", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAiAnalysis(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_ai_analysis", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runAiBatch() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_ai_batch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async investigate(query: string, context: string) : Promise<Result<InvestigationResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("investigate", { query, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateMinutes(sessionId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_minutes", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Format the transcript segments using the AI sidecar, incrementally from the last formatted position.
 * 
 * # Errors
 * 
 * Returns `AppError::AiAnalysis` if the bridge request fails or no new segments are available.
 */
async formatTranscript(sessionId: string) : Promise<Result<FormattedTranscript, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("format_transcript", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggest follow-up questions based on the current transcript and summary.
 * 
 * # Errors
 * 
 * Returns `AppError::AiAnalysis` if the bridge request fails or the response is malformed.
 */
async suggestQuestions(sessionId: string) : Promise<Result<QuestionSuggestion[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_questions", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDiarization() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_diarization") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopDiarization() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_diarization") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runDiarization(audioPath: string, numSpeakers: number | null) : Promise<Result<DiarizedSegment[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_diarization", { audioPath, numSpeakers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpeakers(sessionId: string) : Promise<Result<SpeakerInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_speakers", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSpeakerLabel(id: string, label: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_speaker_label", { id, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleMiniView() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mini_view") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusMainWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchTranscripts(query: string, sessionId: string | null) : Promise<Result<SearchResult[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_transcripts", { query, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSetting(key: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllSettings() : Promise<Result<Partial<{ [key in string]: string }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate a markdown export for a session.
 */
async exportMarkdown(options: ExportOptions) : Promise<Result<ExportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_markdown", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save exported content to the user's Documents directory.
 * 
 * Returns the absolute path of the written file.
 */
async saveExportFile(content: string, filename: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_export_file", { content, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSidecarStatus() : Promise<Result<SidecarStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_sidecar_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWhisperModelStatus(model: string) : Promise<Result<WhisperModelStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_whisper_model_status", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadWhisperModel(model: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_whisper_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a bookmark for a session, optionally linked to a specific segment.
 * 
 * # Parameters
 * 
 * * `storage` - Injected SQLite storage state.
 * * `session_id` - The session to attach the bookmark to.
 * * `segment_id` - Optional segment ID to link the bookmark to.
 * * `note` - Optional freeform note.
 * 
 * # Returns
 * 
 * The UUID of the newly created bookmark.
 * 
 * # Errors
 * 
 * Returns `AppError::Storage` when the insert fails.
 */
async addBookmark(sessionId: string, segmentId: string | null, note: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_bookmark", { sessionId, segmentId, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a bookmark by its ID.
 * 
 * # Parameters
 * 
 * * `storage` - Injected SQLite storage state.
 * * `id` - UUID of the bookmark to remove.
 * 
 * # Errors
 * 
 * Returns `AppError::Storage` when the bookmark is not found or the delete fails.
 */
async removeBookmark(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_bookmark", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve all bookmarks for a session.
 * 
 * # Parameters
 * 
 * * `storage` - Injected SQLite storage state.
 * * `session_id` - The session whose bookmarks should be retrieved.
 * 
 * # Returns
 * 
 * A list of bookmarks ordered by creation time ascending.
 * 
 * # Errors
 * 
 * Returns `AppError::Storage` when the query fails.
 */
async getBookmarks(sessionId: string) : Promise<Result<Bookmark[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_bookmarks", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate a PDF export for a session.
 * 
 * Fetches session data via `export_markdown` (full transcript with all sections),
 * then converts the generated Markdown to a PDF document.
 * 
 * # Parameters
 * 
 * * `storage` - Injected SQLite storage state.
 * * `session_id` - The session to export.
 * 
 * # Returns
 * 
 * Raw PDF bytes ready to be saved or transferred.
 * 
 * # Errors
 * 
 * Returns `AppError` when session data cannot be fetched or PDF generation fails.
 */
async exportPdf(sessionId: string) : Promise<Result<number[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_pdf", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild the FTS5 search index for a specific session.
 * 
 * # Parameters
 * 
 * * `storage` - Injected SQLite storage state.
 * * `session_id` - The session whose FTS index should be rebuilt.
 * 
 * # Errors
 * 
 * Returns `AppError::Storage` when the index rebuild fails.
 */
async rebuildSearchIndex(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_search_index", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application-wide error type.
 */
export type AppError = { AudioCapture: string } | { SpeechRecognition: string } | { AiAnalysis: string } | { Storage: string } | { Config: string } | { Permission: string } | { Internal: string }
/**
 * A user-created bookmark that marks a specific point in a session's transcript.
 */
export type Bookmark = { 
/**
 * Unique identifier for the bookmark (UUID v4).
 */
id: string; 
/**
 * The session this bookmark belongs to.
 */
session_id: string; 
/**
 * Optional reference to a specific transcript segment.
 */
segment_id: string | null; 
/**
 * Optional freeform note attached to the bookmark.
 */
note: string | null; 
/**
 * ISO 8601 timestamp of when the bookmark was created.
 */
created_at: string }
export type CaptureState = "Idle" | "Capturing" | "Paused"
/**
 * A single speaker-attributed time segment from diarization.
 */
export type DiarizedSegment = { speaker: string; start: number; end: number }
/**
 * Options controlling which sections appear in the exported document.
 */
export type ExportOptions = { session_id: string; include_summary: boolean; include_actions: boolean; include_keywords: boolean; include_transcript: boolean }
/**
 * The generated export content and suggested filename.
 */
export type ExportResult = { content: string; filename: string }
/**
 * A formatted transcript with speaker labels and timestamps applied.
 */
export type FormattedTranscript = { 
/**
 * The formatted transcript text with speaker labels.
 */
formatted_text: string; 
/**
 * End timestamp in milliseconds of the last processed segment.
 */
last_segment_end_ms: number }
/**
 * Result of an on-demand investigation query.
 */
export type InvestigationResult = { id: string; query: string; summary: string; details: string; sources: Source[]; created_at: number }
/**
 * A suggested question for the meeting participant.
 */
export type QuestionSuggestion = { 
/**
 * Unique identifier for the suggestion.
 */
id: string; 
/**
 * The suggested question text.
 */
text: string; 
/**
 * Why this question is suggested based on the conversation context.
 */
reason: string }
export type SearchResult = { segment_id: number; session_id: string; text: string; highlighted: string; start_time: number; end_time: number; speaker: string | null }
export type SidecarStatus = { ai_available: boolean; diarization_available: boolean }
/**
 * A source reference from web search.
 */
export type Source = { title: string; url: string }
/**
 * Metadata about a recognized speaker.
 */
export type SpeakerInfo = { id: string; label: string; color: string; is_self: boolean }
export type WhisperModelStatus = "NotDownloaded" | { Downloading: { progress: number } } | { Ready: { path: string } }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
