/* eslint-disable */
// This file was generated by tauri-specta. Do not edit.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeAudioCapture() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCaptureState() : Promise<Result<CaptureState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_capture_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSession(title: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endSession(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkScreenCapturePermission() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_screen_capture_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startAiAnalysis(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_ai_analysis", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAiAnalysis(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_ai_analysis", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runAiBatch() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_ai_batch") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async investigate(query: string, context: string) : Promise<Result<InvestigationResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("investigate", { query, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateMinutes(sessionId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_minutes", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDiarization() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_diarization") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopDiarization() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_diarization") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runDiarization(audioPath: string, numSpeakers: number | null) : Promise<Result<DiarizedSegment[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_diarization", { audioPath, numSpeakers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSpeakers(sessionId: string) : Promise<Result<SpeakerInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_speakers", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleMiniView() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_mini_view") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusMainWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchTranscripts(query: string, sessionId: string | null) : Promise<Result<SearchResult[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_transcripts", { query, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSetting(key: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllSettings() : Promise<Result<Partial<{ [key in string]: string }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate a markdown export for a session.
 */
async exportMarkdown(options: ExportOptions) : Promise<Result<ExportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_markdown", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save exported content to the user's Documents directory.
 * 
 * Returns the absolute path of the written file.
 */
async saveExportFile(content: string, filename: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_export_file", { content, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Translate all segments for a session into the specified target language.
 * 
 * For each segment the function builds a prompt, sends it through the AI
 * bridge, persists the result, and returns the full list of translations.
 * When the bridge runs in stub mode the translated text is a simple
 * `[Translation] <original>` prefix so that the feature can be exercised
 * without an API key.
 */
async translateSegments(sessionId: string, targetLang: string) : Promise<Result<TranslationEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("translate_segments", { sessionId, targetLang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve previously stored translations for a session.
 */
async getTranslations(sessionId: string, targetLang: string) : Promise<Result<TranslationEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_translations", { sessionId, targetLang }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findRelatedMeetings(sessionId: string) : Promise<Result<MeetingLink[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_related_meetings", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMeetingLinks(sessionId: string) : Promise<Result<MeetingLink[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_links", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Analyse sentiment for every segment in a session.
 * 
 * In stub mode (no real AI backend), generates deterministic mock
 * sentiments cycling through emotion labels. Results are persisted
 * and returned.
 */
async analyzeSentiment(sessionId: string) : Promise<Result<SentimentEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_sentiment", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve previously computed sentiments for a session.
 */
async getSentiments(sessionId: string) : Promise<Result<SentimentEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sentiments", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addDictionaryKeyword(term: string, reading: string | null, definition: string | null, category: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictionary_keyword", { term, reading, definition, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDictionaryKeyword(id: number, term: string, reading: string | null, definition: string | null, category: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary_keyword", { id, term, reading, definition, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDictionaryKeyword(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictionary_keyword", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllDictionaryKeywords() : Promise<Result<DictionaryKeyword[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_dictionary_keywords") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSidecarStatus() : Promise<Result<SidecarStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_sidecar_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWhisperModelStatus(model: string) : Promise<Result<WhisperModelStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_whisper_model_status", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadWhisperModel(model: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_whisper_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application-wide error type.
 */
export type AppError = { AudioCapture: string } | { SpeechRecognition: string } | { AiAnalysis: string } | { Storage: string } | { Config: string } | { Permission: string } | { Internal: string }
export type CaptureState = "Idle" | "Capturing" | "Paused"
/**
 * A single speaker-attributed time segment from diarization.
 */
export type DiarizedSegment = { speaker: string; start: number; end: number }
/**
 * A user-defined keyword with optional reading and definition.
 */
export type DictionaryKeyword = { id: number; term: string; 
/**
 * Japanese reading (furigana).
 */
reading: string | null; definition: string | null; 
/**
 * One of "tech_term", "proper_noun", "acronym", or "custom".
 */
category: string; created_at: string; updated_at: string }
/**
 * Options controlling which sections appear in the exported document.
 */
export type ExportOptions = { session_id: string; include_summary: boolean; include_actions: boolean; include_keywords: boolean; include_transcript: boolean }
/**
 * The generated export content and suggested filename.
 */
export type ExportResult = { content: string; filename: string }
/**
 * Result of an on-demand investigation query.
 */
export type InvestigationResult = { id: string; query: string; summary: string; details: string; sources: Source[]; created_at: number }
export type MeetingLink = { id: number; session_id: string; related_session_id: string; related_title: string; similarity_score: number; shared_keywords: string[]; created_at: string }
export type SearchResult = { segment_id: number; session_id: string; text: string; highlighted: string; start_time: number; end_time: number; speaker: string | null }
/**
 * A single sentiment/tone analysis result for a transcript segment.
 */
export type SentimentEntry = { id: number; session_id: string; segment_id: number; 
/**
 * Sentiment score from -1.0 (very negative) to 1.0 (very positive).
 */
score: number; 
/**
 * Detected emotion label: "neutral", "positive", "negative",
 * "excited", "concerned", or "confused".
 */
emotion: string; 
/**
 * Confidence of the analysis, 0.0 to 1.0.
 */
confidence: number; 
/**
 * Segment start_time, used for timeline plotting.
 */
timestamp: number; created_at: string }
export type SidecarStatus = { ai_available: boolean; diarization_available: boolean }
/**
 * A source reference from web search.
 */
export type Source = { title: string; url: string }
/**
 * Metadata about a recognized speaker.
 */
export type SpeakerInfo = { id: string; label: string; color: string; is_self: boolean }
/**
 * A persisted translation of a transcript segment.
 */
export type TranslationEntry = { id: number; session_id: string; segment_id: number; source_lang: string; target_lang: string; source_text: string; translated_text: string; created_at: string }
export type WhisperModelStatus = "NotDownloaded" | { Downloading: { progress: number } } | { Ready: { path: string } }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
