/* eslint-disable */
// This file was generated by tauri-specta. Do not edit.

import { invoke as tauriInvoke } from "@tauri-apps/api/core";

// Type definitions from Rust backend
export type AppError =
  | { AudioCapture: string }
  | { SpeechRecognition: string }
  | { AiAnalysis: string }
  | { Storage: string }
  | { Config: string }
  | { Permission: string }
  | { Internal: string };

// Commands
export async function healthCheck(): Promise<string> {
  return await tauriInvoke("health_check");
}
